=== Balistiks/xml-kt2/hotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="hotel">
    <xs:complexType>
      <xs:all>
        <xs:element name="visitors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="visitor" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="surname" type="xs:string" />
                    <xs:element name="lastname" type="xs:string" />
                    <xs:element name="age" type="xs:int" />
                    <xs:element name="phone" type="xs:string" />
                    <xs:element name="number_room" type="xs:int" />
                    <xs:element name="cost_room" type="xs:string" />
                  </xs:all>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="staff">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="staf" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="job" type="xs:string" />
                    <xs:element name="age" type="xs:int" />
                    <xs:element name="salary" type="xs:string" />
                    <xs:element name="term_work" type="xs:string" />
                  </xs:all>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="rooms">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="room" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="number" type="xs:int" />
                    <xs:element name="size" type="xs:string" />
                    <xs:element name="bed_count" type="xs:int" />
                    <xs:element name="class" type="xs:string" />
                  </xs:all>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="breakfasts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="breakfast" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="eat_count" type="xs:int" />
                    <xs:element name="cost" type="xs:int" />
                    <xs:element name="star" type="xs:int" />
                  </xs:all>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="raspisanie_uborki">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="raspisanie" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="time" type="xs:string" />
                    <xs:element name="staff_count" type="xs:int" />
                    <xs:element name="item_count" type="xs:int" />
                    <xs:element name="cost" type="xs:int" />
                  </xs:all>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Balistiks/xml-kt2/hotel.xml
<?xml version="1.0" encoding="UTF-8"?>

<hotel
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./hotel.xsd"
    >
    <visitors>
        <visitor id="id_1">
            <name>
                Алексей
            </name>
            <surname>
                Аксеев
            </surname>
            <lastname>
                Алексеев
            </lastname>
            <age>
                18
            </age>
            <phone>
                +79084550075
            </phone>
            <number_room>
                100
            </number_room>
            <cost_room>
                1000$
            </cost_room>
        </visitor>
        <visitor id="id_2">
            <name>
                Владимир
            </name>
            <surname>
                Владимиров
            </surname>
            <lastname>
                Владимирович
            </lastname>
            <age>
                21
            </age>
            <phone>
                +79025438770
            </phone>
            <number_room>
                121
            </number_room>
            <cost_room>
                700$
            </cost_room>
        </visitor>
        <visitor id="id_3">
            <name>
                Борис
            </name>
            <surname>
                Борисов
            </surname>
            <lastname>
                Борисович
            </lastname>
            <age>
                25
            </age>
            <phone>
                +79225551025
            </phone>
            <number_room>
                221
            </number_room>
            <cost_room>
                1900$
            </cost_room>
        </visitor>
        <visitor id="id_4">
            <name>
                Генадий
            </name>
            <surname>
                Генадиев
            </surname>
            <lastname>
                Генадиевич
            </lastname>
            <age>
                21
            </age>
            <phone>
                +79224352135
            </phone>
            <number_room>
                90
            </number_room>
            <cost_room>
                600$
            </cost_room>
        </visitor>
        <visitor id="id_5">
            <name>
                Дмитрий
            </name>
            <surname>
                Дмитриев
            </surname>
            <lastname>
                Дмитриевич
            </lastname>
            <age>
                23
            </age>
            <phone>
                +79023451135
            </phone>
            <number_room>
                310
            </number_room>
            <cost_room>
                2600$
            </cost_room>
        </visitor>
        <visitor id="id_6">
            <name>
                Рома
            </name>
            <surname>
                Романов
            </surname>
            <lastname>
                Романович
            </lastname>
            <age>
                27
            </age>
            <phone>
                +79094252011
            </phone>
            <number_room>
                201
            </number_room>
            <cost_room>
                1600$
            </cost_room>
        </visitor>
        <visitor id="id_7">
            <name>
                Олег
            </name>
            <surname>
                Олегов
            </surname>
            <lastname>
                Олегович
            </lastname>
            <age>
                20
            </age>
            <phone>
                +79112421115
            </phone>
            <number_room>
                190
            </number_room>
            <cost_room>
                1100$
            </cost_room>
        </visitor>
        <visitor id="id_8">
            <name>
                Обрам
            </name>
            <surname>
                Обрамов
            </surname>
            <lastname>
                Обрамович
            </lastname>
            <age>
                20
            </age>
            <phone>
                +79121251815
            </phone>
            <number_room>
                198
            </number_room>
            <cost_room>
                1400$
            </cost_room>
        </visitor>
        <visitor id="id_9">
            <name>
                Владислав
            </name>
            <surname>
                Владиславов
            </surname>
            <lastname>
                Владиславович
            </lastname>
            <age>
                25
            </age>
            <phone>
                +79773221995
            </phone>
            <number_room>
                217
            </number_room>
            <cost_room>
                1900$
            </cost_room>
        </visitor>
        <visitor id="id_10">
            <name>
                Захар
            </name>
            <surname>
                Захаров
            </surname>
            <lastname>
                Захарович
            </lastname>
            <age>
                29
            </age>
            <phone>
                +79016541785
            </phone>
            <number_room>
                406
            </number_room>
            <cost_room>
                5400$
            </cost_room>
        </visitor>
        <visitor id="id_11">
            <name>
                Александра
            </name>
            <surname>
                Александрова
            </surname>
            <lastname>
                Алексеевна
            </lastname>
            <age>
                19
            </age>
            <phone>
                +79082502825
            </phone>
            <number_room>
                98
            </number_room>
            <cost_room>
                400$
            </cost_room>
        </visitor>
        <visitor id="id_12">
            <name>
                Василий
            </name>
            <surname>
                Василиев
            </surname>
            <lastname>
                Василиевич
            </lastname>
            <age>
                22
            </age>
            <phone>
                +79726755455
            </phone>
            <number_room>
                178
            </number_room>
            <cost_room>
                1340$
            </cost_room>
        </visitor>
        <visitor id="id_13">
            <name>
                Денис
            </name>
            <surname>
                Денисов
            </surname>
            <lastname>
                Денисович
            </lastname>
            <age>
                23
            </age>
            <phone>
                +79665414342
            </phone>
            <number_room>
                500
            </number_room>
            <cost_room>
                10000$
            </cost_room>
        </visitor>
        <visitor id="id_14">
            <name>
                Данила
            </name>
            <surname>
                Данилов
            </surname>
            <lastname>
                Данилович
            </lastname>
            <age>
                22
            </age>
            <phone>
                +79023457071
            </phone>
            <number_room>
                321
            </number_room>
            <cost_room>
                3400$
            </cost_room>
        </visitor>
        <visitor id="id_15">
            <name>
                Макар
            </name>
            <surname>
                Макаров
            </surname>
            <lastname>
                Макарович
            </lastname>
            <age>
                18
            </age>
            <phone>
                +79077067771
            </phone>
            <number_room>
                171
            </number_room>
            <cost_room>
                900$
            </cost_room>
        </visitor>
    </visitors>
    <staff>
        <staf id="id1">
            <name>
                Захар
            </name>
            <job>
                Администратор
            </job>
            <age>
                21
            </age>
            <salary>
                600$
            </salary>
            <term_work>
                5 лет
            </term_work>
        </staf>
        <staf id="id2">
            <name>
                Захар
            </name>
            <job>
                Администратор
            </job>
            <age>
                21
            </age>
            <salary>
                600$
            </salary>
            <term_work>
                5 лет
            </term_work>
        </staf>
        <staf id="id3">
            <name>
                Захар
            </name>
            <job>
                Администратор
            </job>
            <age>
                21
            </age>
            <salary>
                600$
            </salary>
            <term_work>
                5 лет
            </term_work>
        </staf>
        <staf id="id4">
            <name>
                Захар
            </name>
            <job>
                Администратор
            </job>
            <age>
                21
            </age>
            <salary>
                600$
            </salary>
            <term_work>
                5 лет
            </term_work>
        </staf>
        <staf id="id5">
            <name>
                Захар
            </name>
